version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "t25prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-13n55ugs28wd5"
s3_prefix = "t25prod"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "ClientDomains=\"http://localhost:3000\" AdminEmail=\"wharri8@g.clemson.edu\""
