version: '3'

services:

  mysql-development:
    #    image: arm64v8/mysql:latest
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: testapp
    ports:
      - "3308:3306"
